# Generated by Django 5.2.15 on 2026-07-05 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_student_profile_photo_alter_faculty_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('notification_type', models.CharField(choices=[('ASSIGNMENT_DUE', 'Assignment Due Soon'), ('ASSIGNMENT_SUBMITTED', 'Assignment Submitted'), ('MATERIAL_COMPLETED', 'Study Material Completed'), ('LIVE_SESSION_UPCOMING', 'Live Session Upcoming'), ('LIVE_SESSION_LIVE', 'Live Session Live'), ('PROFILE_UPDATED', 'Profile Updated')], max_length=50)),
                ('target_url', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='lms.student')),
            ],
        ),
    ]
